@echo Installing clash for windows...
winget install Fndroid.ClashForWindows
::start "" "C:\Program Files\clash for windows\Clash for Windows.exe"
::QQ微软商店版
@echo Installing QQ微软商店版...
winget install --id=XPFP03DHSN0S5K --accept-package-agreements
@echo Installing chrome...
winget install --id=google.chrome -e
@echo Installing 微信...
winget install --id=Tencent.WeChat -e
@echo Installing 网易云音乐...
winget install --id=NetEase.CloudMusic -e
@echo Installing Snipaste截图工具...
winget install --id=Snipaste -e
@echo Installing PotPlayer...
winget install --id=Daum.PotPlayer -e
@echo 修改Hosts,屏蔽potplayer广告
cd C:\Windows\System32\drivers\etc
@echo *.ad.daum.net 127.0.0.1 >>hosts
@echo *.edge4k.com 127.0.0.1 >>hosts
@echo *.kgslb.com 127.0.0.1 >>hosts
@echo Installing PowerToys...
winget install Microsoft.PowerToys --source winget
@echo Installing WindowsTerminal...
winget install --id=Microsoft.WindowsTerminal -e
@echo Installing 百度云网盘...
winget install --id=Baidu.BaiduNetdisk -e
@echo Installing 7zip...
winget install 7zip.7zip
@echo Installing 迅雷...
winget install --id=XunLei.xunlei -e
@echo Installing GeForceExperience...
winget install Nvidia.GeForceExperience


